### ISSUE TITLE
rsync issue?

### ISSUE THREAD

**Issue by franklinr** [TalkBank/shiny-vagrant#5]
I updated the shiny Rmd code, so that it would be more responsive, but it doesn't seem to be loaded.  For example, when you start childes2csv, it should only load 1000 lines, but it is loading 10000 lines.  Maybe rsync is not copying the new files over?  If you are still sorting things out, please ignore this.

**Comment by macw** [comment]
I think Franklin is offline now and I don’t know what I would have to do to fire up rsync.  Perhaps he can chime in later today or tomorrow.  

-Brian

**Comment by FranklinChen** [comment]
Is this still not happening? Note that we have apparently around a several-hour (or longer) lag in between when our server is actually updated with the latest materials, because someone needs to run `git pull` and `vagrant reload` and `vagrant provision` and that's usually me but we're in different time zones.

**Comment by franklinr** [comment]
Maxsize is still 10000 rather than 1000.  So it doesn't seem to be copying the new files, maybe because the server is full.
http://gandalf.talkbank.org:8080/childes2csv/
I don't know if you want to do this, but there is something called webhooks that will tell you when there are changes and automatically run git pull, vagrant reload and provision (perhaps after a 15 minute delay, in case there are multiple changes).
https://stackoverflow.com/questions/31175338/ubuntu-automatically-pull-from-github-repo
I have no idea how to set this up.

**Comment by macw** [comment]
Perhaps it would help to explain where the files are located right now.  The machine in a Mac Pro with a 250GB internal hard drive.  The vagrant is installed in ~/shiny-vagrant on that disk.  To avoid the storage limitation, I placed the three big folders onto the 2TB external at /Volumes/New and set up a symbolic link to each of the three from the /storage folder.  However, it appears that this didn’t work, because the scripts are putting things back into the ~/shiny-vagrant on the smaller internal drive.  So, to avoid this, I now created symbolic links from the folders on the external directly into ~/shiny-vagrant/storage.  Then I deleted the three (duplicate) folders on the internal drive in /storage.  That freed up 125 GB of space.  

Perhaps this will help.  If so, it is just important to create these three big folders at /Volumes/New instead of inside /storage.

—Brian

**Comment by franklinr** [comment]
I've removed the rsync in sync-from-extras.sh, so the storage files should not be copied anymore.  So this new version should work.  Can you update git and reload the vagrant?

**Comment by FranklinChen** [comment]
Things don't work at all now:

```
$ ./sync-from-extras.sh
rm: ./storage/csvcorpora: is a directory
rm: ./storage/ngrams: is a directory
rm: ./storage/actualcsv: is a directory
```

I think these directories need to be removed from the Git repo?

**Comment by macw** [comment]
Yes, that makes sense, as long as you don't delete the folders with the actual materials on the external drive.

**Comment by macw** [comment]
Things seem to be working.  I updated git and reload the vagrant using the command in ~/shiny-vagrant

GANDALF:~ macw$ cd shiny-vagrant
GANDALF:shiny-vagrant macw$ ./sync-from-extras.sh
ln: ./storage/csvcorpora/csvcorpora: File exists
ln: ./storage/ngrams/ngrams: File exists
ln: ./storage/actualcsv/actualcsv: File exists
GANDALF:shiny-vagrant macw$ 

I don’t quite get the configuration of the symbolic links, but if this works then I guess this is fine.  

—Brian

**Comment by franklinr** [comment]
The shiny files are still not updated.  Can you ssh to the /srv/shiny-server/childes2csv folder and do ls there?  Also, can you check if the childes2csv11.Rmd has this code?
                              choices = c(1000,10000,100000,1000000,10000000,1000000000000),width='90%')
It should give the choice of 1000, but it is not.  I think rsync doesn't think they are different, so it is not updating.

**Comment by macw** [comment]
I am attaching a screenshot of the shiny-vagrant folder.  As you see the only thing in childes2csv are two R files.  I don’t know how I am supposed to use those to update things.  

Yes, that line with 1000 is in the *.Rmd file.

—Brian

**Comment by franklinr** [comment]
Thanks for this.  Skype might be good, but I think it would also help if you could send me a few more screenshots.  Can you click on /shiny-vagrant/storage/actualcsv and send me that screenshot?

The childes2csv11.Rmd file above is from the github.  But the problem I think is that it is not being copied to the /srv/shiny-server/childes2csv folder.  So if you can type vagrant ssh and then "cd /srv/shiny-server/childes2csv" and type "ls" and send me a screenshot, I can confirm if share3.R is copied to the linux machine. 
  It would also be good to confirm that the actualcsv folder is available on the linux machine.  Can you "cd /srv/shiny-server/storage/actualcsv" and send me a screen shot of the output of "ls"?

thanks

**Comment by macw** [comment]
From the screenshots it appears that the symbolic links may not be working.  Perhaps it would be best to put the everything on the external drive to avoid the symbolic link problem.

—Brian

**Comment by franklinr** [comment]
How are you setting up the symbolic links?  Are you going into terminal and typing
ln -s /Volume/New/extras/actualcsv ~/shiny-vagrant/storage/actualcsv
ln -s /Volume/New/extras/csvcorpora ~/shiny-vagrant/storage/csvcorpora
ln -s /Volume/New/extras/ngrams ~/shiny-vagrant/storage/ngrams
I don't know the source folder, so you will need to change these to match your actual path.

**Comment by macw** [comment]
The symbolic links were not right.  They looked okay to Unix, but not to OSX.  I recreated them and they seem okay now to both, but the problem is not solved.  Also,  after I run vagrant reload and vagrant provision, these additional spurious symbolic links are getting created.  

I don’t think we can solve this except through a Skype call. As I said, I am available all afternoon now and most of the day tomorrow.

—Brian

**Comment by franklinr** [comment]
Ok, I have to teach tomorrow, so I can't do it until Tuesday my time.  Can you send me a screenshot of the ~/shiny-vagrant/storage/actualcsv?  Also, which spurious symbolic links are you talking about?

**Comment by franklinr** [comment]
this is fixed
